-d D:\Vscode\FPGA\GOWIN\motor_top\impl\gwsynthesis\motor_top.vg
-p GW2A-55C-PBGA484-8
-pn GW2A-LV55PG484C8/I7
-cst D:\Vscode\FPGA\GOWIN\motor_top\src\motor_top.cst
-cfg D:\Vscode\FPGA\GOWIN\motor_top\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
